server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO 