server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: auth-service
  datasource:
    url: ${SUPABASE_AUTH_DB_URL}
    username: ${SUPABASE_AUTH_DB_USER}
    password: ${SUPABASE_AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
jwt:
  secret: makestar-secret-key-for-jwt-token-generation-and-validation-should-be-very-long
  access-token-expiration: 3600000 # 1시간
  refresh-token-expiration: 604800000 # 7일
management:
  endpoints:
    web:
      exposure:
        include: health,info
