## 인증 서비스 설정

# 서버 설정
server:
  port: 8081

# Spring 설정
spring:
  application:
    name: auth-service
  # 공통 프로파일 활성화
  profiles:
    include: commons
  
  # 데이터베이스 설정
  datasource:
    url: ${SUPABASE_AUTH_DB_URL}
    username: ${SUPABASE_AUTH_DB_USER}
    password: ${SUPABASE_AUTH_DB_PASSWORD}

# 로깅 설정
logging:
  level:
    com.makestar.auth: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.security: INFO
