server:
  port: 8084

# Spring 설정
spring:
  application:
    name: history-service
  cloud:
    config:
      import-check:
        enabled: false
  # 데이터베이스 설정
  datasource:
    url: ${SUPABASE_HISTORY_DB_URL}
    username: ${SUPABASE_HISTORY_DB_USER}
    password: ${SUPABASE_HISTORY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: history-service-pool
      # connection-test-query: SELECT 1
      validation-timeout: 30000
  # JPA 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Eureka 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

# 관리 엔드포인트 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 로깅 설정
logging:
  level:
    com.makestar.history: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
# 데이터 보존 기간 설정 (일 단위)
history:
  retention:
    activity:
      normal: 365 # 일반 활동 데이터 보존 (1년)
      sensitive: 30 # 민감한 활동 데이터 보존 (30일)
    error:
      normal: 180 # 일반 오류 로그 보존 (6개월)
      critical: 365 # 심각한 오류 로그 보존 (1년) 

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.makestar.history
  default-consumes-media-type: application/json
  default-produces-media-type: application/json 
