## 히스토리 서비스 설정

# 서버 설정
server:
  port: 8084

# Spring 설정
spring:
  application:
    name: history-service
  # 공통 프로파일 활성화
  profiles:
    include: commons
  # 데이터베이스 설정
  datasource:
    url: ${SUPABASE_HISTORY_DB_URL}
    username: ${SUPABASE_HISTORY_DB_USER}
    password: ${SUPABASE_HISTORY_DB_PASSWORD}

# 로깅 설정
logging:
  level:
    com.makestar.history: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    
# 데이터 보존 기간 설정 (일 단위)
history:
  retention:
    activity:
      normal: 365 # 일반 활동 데이터 보존 (1년)
      sensitive: 30 # 민감한 활동 데이터 보존 (30일)
    error:
      normal: 180 # 일반 오류 로그 보존 (6개월)
      critical: 365 # 심각한 오류 로그 보존 (1년) 
