server:
  port: 8083

# Spring 설정
spring:
  application:
    name: chat-service
  cloud:
    config:
      import-check:
        enabled: false
  # 데이터베이스 설정
  datasource:
    url: ${SUPABASE_CHAT_DB_URL}
    username: ${SUPABASE_CHAT_DB_USER}
    password: ${SUPABASE_CHAT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: chat-service-pool
      # connection-test-query: SELECT 1
      validation-timeout: 30000
  # MongoDB 설정
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chatdb}
  # JPA 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Eureka 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

# 관리 엔드포인트 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 로깅 설정
logging:
  level:
    com.makestar.chat: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.makestar.chat
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
