## 채팅 서비스 설정

# 서버 설정
server:
  port: 8083

# Spring 설정
spring:
  application:
    name: chat-service
  # 공통 프로파일 활성화
  profiles:
    include: commons
  # 데이터베이스 설정
  datasource:
    url: ${SUPABASE_CHAT_DB_URL}
    username: ${SUPABASE_CHAT_DB_USER}
    password: ${SUPABASE_CHAT_DB_PASSWORD}
  # MongoDB 설정
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chatdb}
  
# 로깅 설정
logging:
  level:
    com.makestar.chat: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
